apiVersion: v1
kind: Service
metadata:
  name: store-api
  namespace: store-dev
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: store-api
  ports:
    - port: 80
      targetPort: http